export const listCards = [
  {
    id: 1,
    imgLogo: "",
    title: "Ecoleta",
    description: "este é um projeto de testes",
    tecnologies: "Web . React . Typescript ",
    developer_link: "/1",
    production_link: "/",
  },
  {
    id: 2,
    imgLogo: "",
    title: "CoffeeCool Cafeteria",
    description: "este é um projeto de testes",
    tecnologies: "React . Typescript . Firebase",
    developer_link: "/1",
    production_link: "/1",
  },
  {
    id: 3,
    imgLogo: "",
    title: "Podcastr",
    description: "este é um projeto de testes",
    tecnologies: "React . Typescript",
    developer_link: "/1",
    production_link: "/",
  },

  {
    id: 4,
    imgLogo: "",
    title: "Dev Finances",
    description: "este é um projeto de testes",
    tecnologies: "web . React . Typescript",
    developer_link: "/1",
    production_link: "/1",
  },
  {
    id: 5,
    imgLogo: "",
    title: "Covid 19 Tracker",
    description: "este é um projeto de testes",
    tecnologies: "web . React Native . Typescript",
    developer_link: "/1",
    production_link: "/1",
  },
];
